import tg_icon from "@/../public/icons/footer/tg_black.svg";
import fb_icon from "@/../public/icons/footer/fb_black.svg";
// import link_icon from "@/../public/icons/footer/Link_black.svg";
import wh_icon from "@/../public/icons/footer/wh_black.svg";
// import ok_icon from "@/../public/icons/footer/ok_black.svg";
import inst_icon from "@/../public/icons/footer/inst_black.svg";
// import youtube_icon from "@/../public/icons/footer/youtube_black.svg";
// import vk_icon from "@/../public/icons/footer/vk_black.svg";
// import tik_tok_icon from "@/../public/icons/footer/Tik_tok_black.svg";

export const footerLinks = [
  {
    href: "https://t.me/SMoliyabank_bot",
    img: tg_icon,
    alt: "tg_icon",
  },
  {
    href: "https://www.facebook.com/share/1FJxG6E3iZ/",
    img: fb_icon,
    alt: "fb_icon",
  },
  {
    href: "https://www.instagram.com/standart_moliya/?igsh=MWx6NXI4cXhtc2IzYQ%3D%3D",
    img: inst_icon,
    alt: "inst_icon",
  },
  {
    href: "tel:+99298754830202",
    img: wh_icon,
    alt: "wh_icon",
  },
  // {
  //   href: "#",
  //   img: link_icon,
  //   alt: "link_icon",
  // },
  // {
  //   href: "#",
  //   img: ok_icon,
  //   alt: "ok_icon",
  // },
  // {
  //   href: "#",
  //   img: youtube_icon,
  //   alt: "youtube_icon",
  // },
  // {
  //   href: "#",
  //   img: vk_icon,
  //   alt: "vk_icon",
  // },
  // {
  //   href: "#",
  //   img: tik_tok_icon,
  //   alt: "tik_tok_icon",
  // },
];

export const regions = [
  {
    label: "Вилойати Мухтори Кӯҳистони Бадахшон",
    value: 1,
    children: [
      { label: "Хоруғ", value: 101 },
      { label: "Ноҳияи Ванҷ", value: 102 },
      { label: "Ноҳияи Дарвоз", value: 103 },
      { label: "Ноҳияи Ишкошим", value: 104 },
      { label: "Ноҳияи Мурғоб", value: 105 },
      { label: "Ноҳияи Роштқалъа", value: 106 },
      { label: "Ноҳияи Рушон", value: 107 },
      { label: "Ноҳияи Шуғнон", value: 108 },
    ],
  },
  {
    label: "Вилояти Суғд",
    value: 2,
    children: [
      { label: "Хуҷанд", value: 201 },
      { label: "Истаравшан", value: 202 },
      { label: "Исфара", value: 203 },
      { label: "Конибодом", value: 204 },
      { label: "Панҷакент", value: 205 },
      { label: "Ноҳияи Айнӣ", value: 206 },
      { label: "Ноҳияи Ашт", value: 207 },
      { label: "Ноҳияи Ғафуров", value: 208 },
      { label: "Ноҳияи Деваштич", value: 209 },
      { label: "Ноҳияи Зафаробод", value: 210 },
      { label: "Ноҳияи Мастчоҳ", value: 211 },
      { label: "Ноҳияи Спитамен", value: 212 },
      { label: "Ноҳияи Ҷаббор Расулов", value: 213 },
      { label: "Ноҳияи Шаҳристон", value: 214 },
    ],
  },
  {
    label: "Вилояти Хатлон",
    value: 3,
    children: [
      { label: "Бохтар", value: 301 },
      { label: "Кӯлоб", value: 302 },
      { label: "Норак", value: 303 },
      { label: "Левакант", value: 304 },
      { label: "Ноҳияи Вахш", value: 305 },
      { label: "Ноҳияи Восеъ", value: 306 },
      { label: "Ноҳияи Данғара", value: 307 },
      { label: "Ноҳияи Ҷалолиддини Балхӣ", value: 308 },
      { label: "Ноҳияи Кубодиён", value: 309 },
      { label: "Ноҳияи Кӯшониён", value: 310 },
      { label: "Ноҳияи Муминабод", value: 311 },
      { label: "Ноҳияи Панҷ", value: 312 },
      { label: "Ноҳияи Темурмалик", value: 313 },
      { label: "Ноҳияи Фархор", value: 314 },
      { label: "Ноҳияи Ховалинг", value: 315 },
      { label: "Ноҳияи Шаҳритус", value: 316 },
      { label: "Ноҳияи Ёвон", value: 317 },
    ],
  },
  {
    label: "Ноҳияҳои тобеи ҷумҳурӣ",
    value: 4,
    children: [
      { label: "Ваҳдат", value: 401 },
      { label: "Ҳисор", value: 402 },
      { label: "Роғун", value: 403 },
      { label: "Турсунзода", value: 404 },
      { label: "Ноҳияи Варзоб", value: 405 },
      { label: "Ноҳияи Ваҳдат", value: 406 },
      { label: "Ноҳияи Ҳисор", value: 407 },
      { label: "Ноҳияи Лахш", value: 408 },
      { label: "Ноҳияи Нуробод", value: 409 },
      { label: "Ноҳияи Рашт", value: 410 },
      { label: "Ноҳияи Роғун", value: 411 },
      { label: "Ноҳияи Рӯдакӣ", value: 412 },
      { label: "Ноҳияи Тоҷикобод", value: 413 },
      { label: "Ноҳияи Турсунзода", value: 414 },
      { label: "Ноҳияи Файзобод", value: 415 },
      { label: "Ноҳияи Шаҳринав", value: 416 },
    ],
  },
  {
    label: "Душанбе",
    value: 5,
    children: [
      { label: "Исмоили Сомонӣ", value: 501 },
      { label: "Синó", value: 502 },
      { label: "Фирдавсӣ", value: 503 },
      { label: "Шоҳмансур", value: 504 },
    ],
  },
];

export const regions2 = [
  { label: "Душанбе", value: 5 },
  { label: "Исмоили Сомонӣ", value: 501 },
  { label: "Сино", value: 502 },
  { label: "Фирдавсӣ", value: 503 },
  { label: "Шоҳмансур", value: 504 },
  { label: "Вилойати Мухтори Кӯҳистони Бадахшон", value: 1 },
  { label: "Хоруғ", value: 101 },
  { label: "Ноҳияи Ванҷ", value: 102 },
  { label: "Ноҳияи Дарвоз", value: 103 },
  { label: "Ноҳияи Ишкошим", value: 104 },
  { label: "Ноҳияи Мурғоб", value: 105 },
  { label: "Ноҳияи Роштқалъа", value: 106 },
  { label: "Ноҳияи Рушон", value: 107 },
  { label: "Ноҳияи Шуғнон", value: 108 },
  { label: "Вилояти Суғд", value: 2 },
  { label: "Хуҷанд", value: 201 },
  { label: "Истаравшан", value: 202 },
  { label: "Исфара", value: 203 },
  { label: "Конибодом", value: 204 },
  { label: "Панҷакент", value: 205 },
  { label: "Ноҳияи Айнӣ", value: 206 },
  { label: "Ноҳияи Ашт", value: 207 },
  { label: "Ноҳияи Ғафуров", value: 208 },
  { label: "Ноҳияи Деваштич", value: 209 },
  { label: "Ноҳияи Зафаробод", value: 210 },
  { label: "Ноҳияи Мастчоҳ", value: 211 },
  { label: "Ноҳияи Спитамен", value: 212 },
  { label: "Ноҳияи Ҷаббор Расулов", value: 213 },
  { label: "Ноҳияи Шаҳристон", value: 214 },
  { label: "Вилояти Хатлон", value: 3 },
  { label: "Бохтар", value: 301 },
  { label: "Кӯлоб", value: 302 },
  { label: "Норак", value: 303 },
  { label: "Левакант", value: 304 },
  { label: "Ноҳияи Вахш", value: 305 },
  { label: "Ноҳияи Восеъ", value: 306 },
  { label: "Ноҳияи Данғара", value: 307 },
  { label: "Ноҳияи Ҷалолиддини Балхӣ", value: 308 },
  { label: "Ноҳияи Кубодиён", value: 309 },
  { label: "Ноҳияи Кӯшониён", value: 310 },
  { label: "Ноҳияи Муминабод", value: 311 },
  { label: "Ноҳияи Панҷ", value: 312 },
  { label: "Ноҳияи Темурмалик", value: 313 },
  { label: "Ноҳияи Фархор", value: 314 },
  { label: "Ноҳияи Ховалинг", value: 315 },
  { label: "Ноҳияи Шаҳритус", value: 316 },
  { label: "Ноҳияи Ёвон", value: 317 },
  { label: "Ноҳияҳои тобеи ҷумҳурӣ", value: 4 },
  { label: "Ваҳдат", value: 401 },
  { label: "Ҳисор", value: 402 },
  { label: "Роғун", value: 403 },
  { label: "Турсунзода", value: 404 },
  { label: "Ноҳияи Варзоб", value: 405 },
  { label: "Ноҳияи Ваҳдат", value: 406 },
  { label: "Ноҳияи Ҳисор", value: 407 },
  { label: "Ноҳияи Лахш", value: 408 },
  { label: "Ноҳияи Нуробод", value: 409 },
  { label: "Ноҳияи Рашт", value: 410 },
  { label: "Ноҳияи Роғун", value: 411 },
  { label: "Ноҳияи Рӯдакӣ", value: 412 },
  { label: "Ноҳияи Тоҷикобод", value: 413 },
  { label: "Ноҳияи Турсунзода", value: 414 },
  { label: "Ноҳияи Файзобод", value: 415 },
  { label: "Ноҳияи Шаҳринав", value: 416 },
];
