import { CurrencyRateT } from "@/types/main-page/ui/types";

export const app_url = process.env.NEXT_PUBLIC_API_URL;

export const currencyRateData = {
  date: "2025-08-15",
  base_flag_url:
    "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/tj.png",
  rates: [
    {
      nbt: 6.0897,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "036",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0313,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "AUD",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "AU",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/au.png",
    },
    {
      nbt: 2.4373,
      nominal: 100,
      card_sale: null,
      wallet_sale: null,
      currency_num: "051",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0024,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "AMD",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "AM",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/am.png",
    },
    {
      nbt: 6.7763,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "124",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0196,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "CAD",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "CA",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ca.png",
    },
    {
      nbt: 1.3009,
      nominal: 1,
      card_sale: 1.309,
      wallet_sale: 1.309,
      currency_num: "156",
      card_purchase: 1.2881,
      exchange_sale: 1.2876,
      transfer_sale: null,
      nbt_difference: -0.0003,
      wallet_purchase: 1.2881,
      exchange_purchase: 1.2451,
      transfer_purchase: null,
      currency_char_code: "CNY",
      card_sale_difference: -0.0002,
      wallet_sale_difference: -0.0002,
      card_purchase_difference: -0.0003,
      exchange_sale_difference: -0.0009,
      transfer_sale_difference: 0,
      wallet_purchase_difference: -0.0003,
      exchange_purchase_difference: -0.0009,
      transfer_purchase_difference: 0,
      country_code: "CN",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/cn.png",
    },
    {
      nbt: 1.4638,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "208",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0052,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "DKK",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "DK",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/dk.png",
    },
    {
      nbt: 0.7621,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "352",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0037,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "ISK",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "IS",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/is.png",
    },
    {
      nbt: 1.0681,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "356",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0029,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "INR",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "IN",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/in.png",
    },
    {
      nbt: 0.2226,
      nominal: 1000,
      card_sale: null,
      wallet_sale: null,
      currency_num: "364",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0002,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "IRR",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "IR",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ir.png",
    },
    {
      nbt: 0.6359,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "392",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: 0.0031,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "JPY",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "JP",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/jp.png",
    },
    {
      nbt: 0.1728,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "398",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0002,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "KZT",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "KZ",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/kz.png",
    },
    {
      nbt: 30.5934,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "414",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0224,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "KWD",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "KW",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/kw.png",
    },
    {
      nbt: 1.069,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "417",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0014,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "KGS",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "KG",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/kg.png",
    },
    {
      nbt: 2.2171,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "458",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0048,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "MYR",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "MY",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/my.png",
    },
    {
      nbt: 0.5313,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "484",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: 0.0,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "MXN",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "MX",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/mx.png",
    },
    {
      nbt: 0.5615,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "498",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: 0.0058,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "MDL",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "MD",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/md.png",
    },
    {
      nbt: 0.919,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "578",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0015,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "NOK",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "NO",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/no.png",
    },
    {
      nbt: 0.3285,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "586",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0004,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "PKR",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "PK",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/pk.png",
    },
    {
      nbt: 2.4911,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "682",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0026,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "SAR",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "SA",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/sa.png",
    },
    {
      nbt: 7.2866,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "702",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0147,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "SGD",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "SG",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/sg.png",
    },
    {
      nbt: 0.9777,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "752",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0052,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "SEK",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "SE",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/se.png",
    },
    {
      nbt: 11.5999,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "756",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0462,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "CHF",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "CH",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ch.png",
    },
    {
      nbt: 0.288,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "764",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0012,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "THB",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "TH",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/th.png",
    },
    {
      nbt: 2.5447,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "784",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0026,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "AED",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "AE",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ae.png",
    },
    {
      nbt: 0.1169,
      nominal: 1,
      card_sale: 0.119,
      wallet_sale: 0.119,
      currency_num: "810",
      card_purchase: 0.1161,
      exchange_sale: 0.116,
      transfer_sale: null,
      nbt_difference: -0.0003,
      wallet_purchase: 0.1161,
      exchange_purchase: 0.114,
      transfer_purchase: null,
      currency_char_code: "RUB",
      card_sale_difference: -0.0018,
      wallet_sale_difference: -0.0018,
      card_purchase_difference: -0.0024,
      exchange_sale_difference: 0.0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: -0.0024,
      exchange_purchase_difference: 0.0,
      transfer_purchase_difference: 0,
      country_code: "RU",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ru.png",
    },
    {
      nbt: 12.6776,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "826",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0024,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "GBP",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "GB",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/gb.png",
    },
    {
      nbt: 9.3472,
      nominal: 1,
      card_sale: 9.4,
      wallet_sale: 9.4,
      currency_num: "840",
      card_purchase: 9.25,
      exchange_sale: 9.38,
      transfer_sale: null,
      nbt_difference: -0.0093,
      wallet_purchase: 9.25,
      exchange_purchase: 9.3,
      transfer_purchase: null,
      currency_char_code: "USD",
      card_sale_difference: 0.0,
      wallet_sale_difference: 0.0,
      card_purchase_difference: 0.0,
      exchange_sale_difference: -0.01,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0.0,
      exchange_purchase_difference: -0.01,
      transfer_purchase_difference: 0,
      country_code: "US",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/us.png",
    },
    {
      nbt: 0.0745,
      nominal: 100,
      card_sale: null,
      wallet_sale: null,
      currency_num: "860",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0005,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "UZS",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "UZ",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/uz.png",
    },
    {
      nbt: 2.8069,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "933",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0165,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "BYN",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "BY",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/by.png",
    },
    {
      nbt: 2.6706,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "934",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0027,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "TMT",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "TM",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/tm.png",
    },
    {
      nbt: 5.4984,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "944",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0055,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "AZN",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "AZ",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/az.png",
    },
    {
      nbt: 0.2286,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "949",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0005,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "TRY",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "TR",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/tr.png",
    },
    {
      nbt: 1.3654,
      nominal: 10,
      card_sale: null,
      wallet_sale: null,
      currency_num: "971",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.002,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "AFN",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "AF",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/af.png",
    },
    {
      nbt: 10.9259,
      nominal: 1,
      card_sale: 10.85,
      wallet_sale: 10.85,
      currency_num: "978",
      card_purchase: 10.65,
      exchange_sale: 10.78,
      transfer_sale: null,
      nbt_difference: -0.038,
      wallet_purchase: 10.78,
      exchange_purchase: 10.58,
      transfer_purchase: null,
      currency_char_code: "EUR",
      card_sale_difference: 0.0,
      wallet_sale_difference: -0.15,
      card_purchase_difference: 0.0,
      exchange_sale_difference: 0.0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0.0,
      exchange_purchase_difference: 0.0,
      transfer_purchase_difference: 0,
      country_code: "EU",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/eu.png",
    },
    {
      nbt: 0.2267,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "980",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: 0.0005,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "UAH",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "UA",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ua.png",
    },
    {
      nbt: 3.4285,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "981",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0396,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "GEL",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "GE",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/ge.png",
    },
    {
      nbt: 2.5657,
      nominal: 1,
      card_sale: null,
      wallet_sale: null,
      currency_num: "985",
      card_purchase: null,
      exchange_sale: null,
      transfer_sale: null,
      nbt_difference: -0.0082,
      wallet_purchase: null,
      exchange_purchase: null,
      transfer_purchase: null,
      currency_char_code: "PLN",
      card_sale_difference: 0,
      wallet_sale_difference: 0,
      card_purchase_difference: 0,
      exchange_sale_difference: 0,
      transfer_sale_difference: 0,
      wallet_purchase_difference: 0,
      exchange_purchase_difference: 0,
      transfer_purchase_difference: 0,
      country_code: "PL",
      country_flag_url:
        "https://ec2-18-156-46-26.eu-central-1.compute.amazonaws.com/currency_rate/flags/pl.png",
    },
  ],
};

export const getCurrencyRate = async (): Promise<CurrencyRateT | null> => {
  try {
    // const response = await fetch(
    //   `${app_url}currency_rate/v1/get_latest_currency_rates/`
    // );
    // const data: CurrencyRateT = await response.json();
    // console.log("data");
    // return data;
    return currencyRateData;
  } catch (error) {
    console.error(error);
    return null;
  }
};
